accounts:
  - name: alice
    coins: ["10000000token", "100000000stake"]
  - name: bob
    coins: ["10000000token"]
validator:
  name: alice
  staked: "100000000stake"
client:
  vuex:
    path: "vue/src/store"
faucet:
  name: bob 
  coins: ["5token"]
